import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import {Navbar} from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

//layout for home page
export const metadata: Metadata = {
    title: "Balangoda Urban Council",
    description: "Generated by create next app",
    icons: {
        icon: '/logo.png',
    },
};

export default function HomeLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <Navbar/>
            {children}
        </div>
    );
}